---
- name: Source OpenStack admin credentials
  shell: "source /etc/kolla/admin-openrc.sh && env"
  register: openrc_env

- name: Create private network
  shell: |
    source /etc/kolla/admin-openrc.sh && \
    openstack network create private-net
  environment: "{{ dict(openrc_env.stdout_lines | map('split', '=') | map('list') | list) }}"

- name: Create private subnet
  shell: |
    source /etc/kolla/admin-openrc.sh && \
    openstack subnet create private-subnet \
      --network private-net \
      --subnet-range 192.168.100.0/24 \
      --gateway 192.168.100.1 \
      --dns-nameserver 8.8.8.8
  environment: "{{ dict(openrc_env.stdout_lines | map('split', '=') | map('list') | list) }}"

- name: Create public network
  shell: |
    source /etc/kolla/admin-openrc.sh && \
    openstack network create public-net \
      --external \
      --provider-network-type flat \
      --provider-physical-network physnet1
  environment: "{{ dict(openrc_env.stdout_lines | map('split', '=') | map('list') | list) }}"

- name: Create public subnet
  shell: |
    source /etc/kolla/admin-openrc.sh && \
    openstack subnet create public-subnet \
      --network public-net \
      --allocation-pool start=10.0.1.200,end=10.0.1.250 \
      --subnet-range 10.0.1.0/24 \
      --gateway 10.0.1.1 \
      --no-dhcp
  environment: "{{ dict(openrc_env.stdout_lines | map('split', '=') | map('list') | list) }}"

- name: Create internal router
  shell: |
    source /etc/kolla/admin-openrc.sh && \
    openstack router create internal-router
  environment: "{{ dict(openrc_env.stdout_lines | map('split', '=') | map('list') | list) }}"

- name: Set router external gateway
  shell: |
    source /etc/kolla/admin-openrc.sh && \
    openstack router set internal-router --external-gateway public-net
  environment: "{{ dict(openrc_env.stdout_lines | map('split', '=') | map('list') | list) }}"

- name: Attach private subnet to router
  shell: |
    source /etc/kolla/admin-openrc.sh && \
    openstack router add subnet internal-router private-subnet
  environment: "{{ dict(openrc_env.stdout_lines | map('split', '=') | map('list') | list) }}"

- name: Allow ICMP (ping) in default security group
  shell: |
    source /etc/kolla/admin-openrc.sh && \
    openstack security group rule create --proto icmp default || true
  environment: "{{ dict(openrc_env.stdout_lines | map('split', '=') | map('list') | list) }}"

- name: Allow SSH in default security group
  shell: |
    source /etc/kolla/admin-openrc.sh && \
    openstack security group rule create --proto tcp --dst-port 22 default || true
  environment: "{{ dict(openrc_env.stdout_lines | map('split', '=') | map('list') | list) }}"
