  heat_template_version: 2016-10-14
  description: Template to spawn an cirros instance.

  parameters:
    metadata:
      type: json
    flavor:
      type: string
      description: instance flavor to be used
      default: m1.micro
    network:
      type: string
      description: project network to attach instance to
      default: private
    external_network:
      type: string
      description: network used for floating IPs
      default: public

  resources:
    server:
      type: OS::Nova::Server
      properties:
        image: cirros-0.5.2-x86_64-disk
        flavor: {get_param: flavor}
        metadata: {get_param: metadata}
        networks:
          - port: { get_resource: port }

    port:
      type: OS::Neutron::Port
      properties:
        network: {get_param: network}
        security_groups:
          - default

    floating_ip:
      type: OS::Neutron::FloatingIP
      properties:
        floating_network: {get_param: external_network}

    floating_ip_assoc:
      type: OS::Neutron::FloatingIPAssociation
      properties:
        floatingip_id: { get_resource: floating_ip }
        port_id: { get_resource: port }